### ISSUE TITLE
Clarification regarding ports

### ISSUE THREAD

**Issue by radaniba** [marklogic-community/ml-jdbc-driver#17]
Hi Team,

I am trying to clarify a point from the documentation. On the setup the ODBC server from Marklogic documentation, the recommended port is 5432, the Postgres defat one.

That said, in the JDBC connection documentation for the driver, you use 8077.

Can I please ask some background information about this port, why this and not the 5432 used to map against the Odbc server setup ?

Sorry naive question but I couldn't find a clear description of this in the documentation

Thanks

**Comment by bobstarbird** [comment]
The port value is configurable.
You are correct that 5432 is a valid value (and so is 8077).
You are free to choose a value that works in your environment.
Often in an enterprise environment the port must be opened through firewalls and network configuration.
8077 was just an arbitrary value in my test environment. 
Hope that helps.
