### ISSUE TITLE
PgConnection.setReadOnly() throws exception whenever you interact with it

### ISSUE THREAD

**Issue by awal11** [marklogic-community/ml-jdbc-driver#2]
I am trying to use the driver together with PrestoDB. I encountered few issues, this would be the one of them.

Presto sets the JDBC driver to read only mode and this triggers an exception 
```
org.postgresql.util.PSQLException: A result was returned when none was expected.
	at org.postgresql.jdbc.PgConnection.execSQLUpdate(PgConnection.java:440)
	at org.postgresql.jdbc.PgConnection.setReadOnly(PgConnection.java:699)
	at Main.main(Main.java:11)
```
no matter what I do
1. without any prior configuration of the connection URL, just by invoking conn.setReadOnly(true);
1. adding readonly=true suggested in Readme.md does nothing because it is case sensitive and should be **readOnly=true**
1. if I add proper readOnly=true to the connection url - it throws exception directly from this line DriverManager.getConnection("jdbc:marklogic://localhost:8077/?readOnly=true","user","pw") as the PG driver was not adopted properly

AFAIK the driver will be always read only so my suggestion is to 
1. get rid of all the code related to handling readOnly
1. fix the readme to indicate it more clearly

Would you accept a pull request to implement it?

**Comment by bobstarbird** [comment]
It looks like there is a difference between how "SET application_name =" and "SET SESSION CHARACTERISTICS AS TRANSACTION" are handled internally. PgConnection execSQLUpdate executeWithFlags checks the results and produces the error because there is a result. The setTransactionIsolation suffers from the same. The solution is not clear to me. Ignoring the boolean is one option.

**Comment by awal11** [comment]
The invocation of setReadOnly is done by presto, beyond my control, so I
think if we want to have the driver usable - we should not throw exceptions
here.
I am not familiar enough with the driver to come up with better ideas than
ignoring the attempt to change the setting.
Btw-I mixed up pull requests for issue 1 and 2, i can redo 2 with separate
branch etc, next week.
