### ISSUE TITLE
PgConnection.setTransactionIsolation() throws exception whenever you interact with it

### ISSUE THREAD

**Issue by awal11** [marklogic-community/ml-jdbc-driver#4]
This issue is pretty similar to #2 
When I want to read the data from ML, some DB pool library tries to reset the transactionIsolation and whatever I try - I get an exception

```
Caused by: org.postgresql.util.PSQLException: A result was returned when none was expected.
	at org.postgresql.jdbc.PgConnection.execSQLUpdate(PgConnection.java:440)
	at org.postgresql.jdbc.PgConnection.setTransactionIsolation(PgConnection.java:838)
````

As the driver is always read only - the easiest solution is to comment out any attempt to change the default setting. 

Let me know if you will accept a pull request for it.

**Comment by bobstarbird** [comment]
I will accept a pull request. I would like to get the repository into a master/branch state and then support the request. And thank you for your major contributions!
